spring:
  datasource:
    url: jdbc:mysql://localhost:3306/channelling_db
    username: channelling
    password: channelling123
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none

  security:
    user:
      name: user
      password: user123
    filter:
      order: 10

application:
  security:
    jwt:
      secret:
        key: 743777217A25432A462D4A614E635266556A586E3272357538782F413F442847
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 days
