spring:
  datasource:
    url: jdbc:mysql://localhost:3306/channelling_db
    username: channelling
    password: channelling123
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none  # Optional: Disable Hibernate's automatic schema creation
