spring:
  datasource:
    url: jdbc:mysql://${ENV_IP}:${ENV_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    user:
      name: user
      password: ${SECURITY_PASSWORD}
    filter:
      order: 10


application:
  security:
    jwt:
      secret:
        key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 days
