spring:
  datasource:
    url: jdbc:mysql:///channelling_db?cloudSqlInstance=channelling-lk-418211:us-central1:my-sql-8&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: channelling
    password: channelling123
    driver-class-name: com.mysql.cj.jdbc.Driver




  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    user:
      name: user
      password: user123
    filter:
      order: 10


application:
  security:
    jwt:
      secret:
        key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
        expiration: 86400000 # 1 day
        refresh-token:
          expiration: 604800000 # 7 days
